### ISSUE TITLE
Hide items secret

### ISSUE THREAD

**Issue by oldeb** [jopeek/fvtt-loot-sheet-npc-5e#175]
When there is a secret ( &lt;section class="secret"&gt;...&lt;/section&gt; ) in an item description, the secret is shown to players when clicking on the item name in the loot table.

![image](https://user-images.githubusercontent.com/6594118/130458077-aa1b0c97-1778-429c-990d-ae49a3dcb63c.png)

The only workaround atm is to link a JounralEntry in the description that contains the secret (or use GM Notes module)

**Comment by DanielBoettner** [comment]
I added this to the styles of the module.

This is untested, but should hide every `.secret` class in an item in the lootsheet when you are not the GM.
```less
 [...]
            .item-summary {
                color: var(--primary-font);
                .secret {
                    display: none;
                }
            }
        }
    }

    &.loot-sheet-npc-gmview {
        .content {
            .tab {
                .item {
                    .item-summary {
                        .secret {
                            display: initial;
                        }
                    }
                }
            }
        }
    }
```

This will be in the release for version **>= 3.4.2.7**.
Please create a new issue, when the coming release does not fix that.
